name: runs on ascend

on:
  workflow_call:
    inputs:
      machine:
        description: If set to other value, the job need ssh
        type: string
        required: false
        default: "ASCEND"
      runner:
        description: Set up the build environment
        type: string
        required: false
        default: "dicp-ascend-ci-910b"

jobs:
  checkout_code:
    name: checkout code
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout Code
        uses: DeepLink-org/deeplink.framework/.github/actions/checkout-code@main

  build_test:
    runs-on: ${{ inputs.runner }}
    needs: checkout_code
    steps:
      - name: build and test on ascend
        uses: DeepLink-org/deeplink.framework/.github/actions/code-build-test@main
        with:
          build_shell: "
              source dicp/scripts/ci/ascend/dipu_env.sh && \
              rm -rf /tmp/torchinductor_autolink/* && \
              rm -rf /tmp/dicp_ascend/* && \
              cd /mnt/cache/share/deeplinkci/dicp_env/transformers && \
              pip uninstall transformers -y && \
              patch -p1 < modeling_llama.diff && patch -p1 < utils.diff && \
              python setup.py clean && \
              python setup.py install --user && \
              patch -R -p1 < modeling_llama.diff && patch -R -p1 < utils.diff && \
              cd - && \
              cd /mnt/cache/share/deeplinkci/dicp_env/accelerate && \
              pip uninstall accelerate -y && \
              python setup.py clean && \
              python setup.py install --user && \
              cd - && \
              pip uninstall torch_dipu -y && \
              pip uninstall dicp -y && \
              cd dipu && python setup.py clean && python setup.py install --user && \
              cd ../dicp && python setup.py clean && python setup.py install --user && \
              source scripts/ci/ascend/test_env.sh /mnt/cache/share/deeplinkci/dicp_env/llama_models && \
              export TEST_DIR=$(pwd)/test && echo ${TEST_DIR} && \
              (bash ${TEST_DIR}/ascend_scripts/ops/run_test_ops.sh false || exit 1) && \
              (bash ${TEST_DIR}/ascend_scripts/models/run_test_models.sh false || exit 1)
            " #Write the script you want to execute here，If you don't know which parameters to fill in, you can refer to the actions/code-build-test
          job_name: "build_test"
          cover_job: "0"
          cleaner: "clean_all_if_error"
